metadata:
  title: Supported Living Services - Harbor Care Services
  description: Outcome-led supported living services that help adults sustain tenancies, build life skills, and increase independence safely.
  schema:
    '@context': https://schema.org
    '@type': Service
    name: Supported Living Services
    description: Outcome-led supported living with person-centred planning
hero:
  heading: Supported Living Services
  subheading: Structured tenancy support that helps adults grow confidence, maintain stability, and progress toward greater independence.
  profileContent:
    supported-living:
      heading: Supported Living Services
      subheading: Structured tenancy support that helps adults grow confidence, maintain stability, and progress toward greater independence.
    dom-care:
      heading: Domiciliary Care Services
      subheading: Reliable home visits that support daily routines, wellbeing, and safer independent living in familiar surroundings.
  primaryCtaText: Speak With Our Team
  primaryCtaHref: /contact
  secondaryCtaText: Explore Support
  secondaryCtaHref: '#specialties'
  imageKey: unsplash-support
  imageAlt: Support worker and resident reviewing supported living goals
outcomesSnapshot:
  heading: Supported Living Outcomes Snapshot
  intro: Key indicators that matter for referral confidence and long-term placement stability.
  stats:
    - value: 92%
      label: Tenancy Sustainment
      detail: Placements remaining stable at 12 months.
    - value: 96%
      label: Family Satisfaction
      detail: Positive feedback on communication, continuity, and outcomes.
    - value: 100%
      label: Mandatory Training Compliance
      detail: Frontline staff up to date on required competencies.
serviceFit:
  badgeLabel: Service Fit
  heading: Who This Supported Living Pathway Is Best For
  intro: Best suited where adults need structured tenancy support with measurable progression and responsive risk management.
  suitableForTitle: Usually a Strong Fit For
  suitableFor:
    - Adults with learning disabilities needing daily structure to sustain tenancies.
    - Referrals requiring clear life-skills milestones and regular review cycles.
    - Families and commissioners prioritising stable, outcome-led support.
  alternativeSupportTitle: Better Directed Elsewhere When
  alternativeSupport:
    - The primary need is short-term clinical intervention without tenancy goals.
    - Support required is limited to brief non-structured visits.
    - No ongoing review framework or measurable outcome tracking is required.
firstThirtyDays:
  heading: What the First 30 Days Looks Like
  intro: Mobilisation focuses on safe onboarding, routine stabilisation, and visible early progress.
  milestones:
    - dayRange: Days 1-7
      title: Referral Confirmation and Risk Baseline
      description: Confirm needs, immediate safeguards, and communication responsibilities with all stakeholders.
      icon: tabler:clipboard-check
    - dayRange: Days 8-14
      title: Plan Activation and Team Matching
      description: Start co-produced routines and assign consistent staff for continuity and trust.
      icon: tabler:users-group
    - dayRange: Days 15-30
      title: First Outcome Review
      description: Check early progress, resolve friction points, and adjust goals for month two.
      icon: tabler:chart-line
pathwaysSection:
  heading: Learning Disability Support Pathways
  subheading: Tailored pathways that build skills, confidence, and independence through consistent, specialist care.
pathways:
  - title: Tenancy and Daily Living Support
    description: Core tenancy support covering routines, risk planning, and independent living milestones.
    icon: tabler:home-2
    imageKey: unsplash-community
    features:
      - Routine establishment
      - Risk planning
      - Independent living goals
  - title: Life Skills Development
    description: Structured coaching for cooking, budgeting, household tasks, and safe daily decision-making.
    icon: tabler:bulb
    imageKey: unsplash-support
    features:
      - Cooking skills
      - Budgeting support
      - Household management
  - title: Community Access
    description: Support for appointments, shopping, and social routines that build confidence.
    icon: tabler:road-sign
    imageKey: unsplash-training
    features:
      - Appointment support
      - Community participation
      - Social confidence
  - title: Complex Needs Support
    description: Joined-up support for learning disability, autism, and mental health needs.
    icon: tabler:shield-check
    imageKey: unsplash-family
    features:
      - Learning disability
      - Autism support
      - Mental health pathways
supportedLivingFeatures:
  heading: Supported Living Quality Markers
  subheading: Delivery standards that keep placements stable, person-centred, and outcome-led.
  features:
    - icon: tabler:user-check
      title: Co-Produced Plans
      description: Goals are set with service users and reviewed with families and professionals.
    - icon: tabler:shield-check
      title: Positive Risk Management
      description: Support teams balance safety with confidence-building and autonomy.
    - icon: tabler:home-heart
      title: Tenancy Sustainment Focus
      description: Practical routines and engagement reduce placement breakdown risk.
faqSection:
  heading: Supported Living Referral FAQs
  intro: Practical answers for families, social workers, and referral coordinators.
  items:
    - question: How quickly can supported living packages begin?
      answer: Start timing depends on complexity and risk, but urgent referrals are prioritised with clear mobilisation milestones.
    - question: How are outcomes reported to stakeholders?
      answer: We run structured review cycles with documented progress against agreed goals and transparent action tracking.
    - question: Can support levels change over time?
      answer: Yes. Support intensity and routines can be adjusted as needs, risks, and goals evolve.
    - question: Do you support transitions from residential care?
      answer: Yes, including tenancy-readiness work, routine stabilisation, and coordinated family/professional liaison.
contactSection:
  heading: Discuss a Supported Living Referral
  intro: Share your requirements and we will map a practical pathway with clear outcomes and governance.
  phoneLabel: 0208 555 0199
  phoneHref: tel:+442085550199
  emailLabel: referrals@harborcare.co.uk
  emailHref: mailto:referrals@harborcare.co.uk
  address: Unit 12, Healthcare Business Park, London, SE1 7PB
